name: Cleanup Expired Data

on:
  schedule:
    # 毎日午前3時に実行
    - cron: '0 3 * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  cleanup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Cleanup expired data for free users
        run: |
          curl -X POST ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}/functions/v1/cleanup-expired-data \
            -H "Authorization: Bearer ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" \
            -H "Content-Type: application/json" 