name: Daily Messages Generation

on:
  schedule:
    # 毎日午前9時（JST）に実行
    - cron: '0 23 * * *'  # UTC 23:00 = JST 08:00
  workflow_dispatch:  # 手動実行も可能

jobs:
  generate-messages:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Daily Messages
      run: |
        curl -X POST ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}/functions/v1/generate-daily-messages \
          -H "Authorization: Bearer ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json"
