name: Daily Streak Reset

on:
  schedule:
    # 日本時間午前0時 = UTC 15:00 (前日)
    - cron: '0 15 * * *'
  workflow_dispatch: # 手動実行も可能

jobs:
  reset-streaks:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Run daily streak reset
      run: |
        curl -X POST ${{ secrets.SUPABASE_URL }}/functions/v1/daily-streak-reset \
          -H "Authorization: Bearer ${{ secrets.SUPABASE_ANON_KEY }}" \
          -H "Content-Type: application/json"
          
    - name: Log completion
      run: |
        echo "Daily streak reset completed at $(date)"
        echo "This job runs at 15:00 UTC (00:00 JST)" 