name: Daily Messages Generation

on:
  schedule:
    # 毎日深夜1時（JST）に実行
    - cron: '0 16 * * *'  # UTC 16:00 = JST 01:00
  workflow_dispatch:  # 手動実行も可能

jobs:
  generate-messages:
    runs-on: ubuntu-latest
    
    steps:
    - name: Trigger Daily Messages
      run: |
        curl -X POST ${{ secrets.API_URL }}/functions/v1/generate-daily-messages \
          -H "Authorization: Bearer ${{ secrets.CRON_SECRET  }}" \
          -H "Content-Type: application/json"
